# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protocol.grpc import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationServiceStub(object):
    """Service for handling replication and consensus between server replicas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEntries = channel.unary_unary(
                '/replication.ReplicationService/AppendEntries',
                request_serializer=replication__pb2.EntriesRequest.SerializeToString,
                response_deserializer=replication__pb2.AckResponse.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/replication.ReplicationService/RequestVote',
                request_serializer=replication__pb2.VoteRequest.SerializeToString,
                response_deserializer=replication__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.ConfirmConnection = channel.unary_unary(
                '/replication.ReplicationService/ConfirmConnection',
                request_serializer=replication__pb2.PeerAddress.SerializeToString,
                response_deserializer=replication__pb2.AckResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """Service for handling replication and consensus between server replicas
    """

    def AppendEntries(self, request, context):
        """AppendEntries RPC is used for:
        1. Leader heartbeat (empty entries array)
        2. Log replication (entries array contains log entries to replicate)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """RequestVote RPC is used by candidates to gather VoteRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmConnection(self, request, context):
        """ConfirmConnection RPC is used to confirm connection between peers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=replication__pb2.EntriesRequest.FromString,
                    response_serializer=replication__pb2.AckResponse.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=replication__pb2.VoteRequest.FromString,
                    response_serializer=replication__pb2.VoteResponse.SerializeToString,
            ),
            'ConfirmConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmConnection,
                    request_deserializer=replication__pb2.PeerAddress.FromString,
                    response_serializer=replication__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """Service for handling replication and consensus between server replicas
    """

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/AppendEntries',
            replication__pb2.EntriesRequest.SerializeToString,
            replication__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/RequestVote',
            replication__pb2.VoteRequest.SerializeToString,
            replication__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/ConfirmConnection',
            replication__pb2.PeerAddress.SerializeToString,
            replication__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
